apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: demo
  labels:
    app: guestbook
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: guestbook
    tier: frontend

