apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: demo
  labels:
    app: redis
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis
    tier: backend

